export const languages = {
"aa": "Afar",
"ab":"Abkhazian",
"ae":"Avestan",
"af":"Afrikaans",
"ak":"Akan",
"am":"Amharic",
"an":"Aragonese",
"ar":"Arabic",
"as":"Assamese",
"av":"Avaric",
"ay":"Aymara",
"az":"Azerbaijani",
"ba":"Bashkir",
"be":"Belarusian",
"bg":"Bulgarian",
"bi":"Bislama",
"bm":"Bambara",
"bn":"Bengali",
"bo":"Tibetan",
"br":"Breton",
"bs":"Bosnian",
"ca":"Catalan",
"ce":"Chechen",
"ch":"Chamorro",
"co":"Corsican",
"cr":"Cree",
"cs":"Czech",
"cu":"Church Slavic",
"cv":"Chuvash",
"cy":"Welsh",
"da":"Danish",
"de":"German",
"dv":"Divehi",
"dz":"Dzongkha",
"ee":"Ewe",
"el":"Modern Greek",
"en":"English",
"eo":"Esperanto",
"es":"Spanish",
"et":"Estonian",
"eu":"Basque",
"fa":"Persian",
"ff":"Fulah",
"fi":"Finnish",
"fj":"Fijian",
"fo":"Faroese",
"fr":"French",
"fy":"Western Frisian",
"ga":"Irish",
"gd":"Gaelic",
"gl":"Galician",
"gn":"Guarani",
"gu":"Gujarati",
"gv":"Manx",
"ha":"Hausa",
"he":"Hebrew",
"hi":"Hindi",
"ho":"Hiri Motu",
"hr":"Croatian",
"ht":"Haitian Creole",
"hu":"Hungarian",
"hy":"Armenian",
"hz":"Herero",
"ia":"Interlingua",
"id":"Indonesian",
"ie":"Interlingue",
"ig":"Igbo",
"ii":"Sichuan Yi",
"ik":"Inupiaq",
"io":"Ido",
"is":"Icelandic",
"it":"Italian",
"iu":"Inuktitut",
"ja":"Japanese",
"jv":"Javanese",
"ka":"Georgian",
"kg":"Kongo",
"ki":"Kikuyu",
"kj":"Kuanyama",
"kk":"Kazakh",
"kl":"Kalaallisut; Greenlandic",
"km":"Central Khmer",
"kn":"Kannada",
"ko":"Korean",
"kr":"Kanuri",
"ks":"Kashmiri",
"ku":"Kurdish",
"kv":"Komi",
"kw":"Cornish",
"ky":"Kirghiz; Kyrgyz",
"la":"Latin",
"lb":"Luxembourgish; Letzeburgesch",
"lg":"Ganda",
"li":"Limburgan; Limburger; Limburgish",
"ln":"Lingala",
"lo":"Lao",
"lt":"Lithuanian",
"lu":"Luba-Katanga",
"lv":"Latvian",
"mg":"Malagasy",
"mh":"Marshallese",
"mi":"Maori",
"mk":"Macedonian",
"ml":"Malayalam",
"mn":"Mongolian",
"mr":"Marathi",
"ms":"Malay",
"mt":"Maltese",
"my":"Burmese",
"na":"Nauru",
"nb":"Norwegian Bokmål",
"nd":"North Ndebele",
"ne":"Nepali",
"ng":"Ndonga",
"nl":"Dutch; Flemish",
"nn":"Norwegian Nynorsk",
"no":"Norwegian",
"nr":"South Ndebele",
"nv":"Navajo; Navaho",
"ny":"Chichewa; Chewa; Nyanja",
"oc":"Occitan (post 1500)",
"oj":"Ojibwa",
"om":"Oromo",
"or":"Oriya",
"os":"Ossetian; Ossetic",
"pa":"Panjabi; Punjabi",
"pi":"Pali",
"pl":"Polish",
"ps":"Pushto; Pashto",
"pt":"Portuguese",
"qu":"Quechua",
"rm":"Romansh",
"rn":"Rundi",
"ro":"Romanian",
"ru":"Russian",
"rw":"Kinyarwanda",
"sa":"Sanskrit",
"sc":"Sardinian",
"sd":"Sindhi",
"se":"Northern Sami",
"sg":"Sango",
"si":"Sinhala",
"sk":"Slovak",
"sl":"Slovenian",
"sm":"Samoan",
"sn":"Shona",
"so":"Somali",
"sq":"Albanian",
"sr":"Serbian",
"ss":"Swati",
"st":"Sotho",
"su":"Sundanese",
"sv":"Swedish",
"sw":"Swahili",
"ta":"Tamil",
"te":"Telugu",
"tg":"Tajik",
"th":"Thai",
"ti":"Tigrinya",
"tk":"Turkmen",
"tl":"Tagalog",
"tn":"Tswana",
"to":"Tonga",
"tr":"Turkish",
"ts":"Tsonga",
"tt":"Tatar",
"tw":"Twi",
"ty":"Tahitian",
"ug":"Uighur",
"uk":"Ukrainian",
"ur":"Urdu",
"uz":"Uzbek",
"ve":"Venda",
"vi":"Vietnamese",
"vo":"Volapük",
"wa":"Walloon",
"wo":"Wolof",
"xh":"Xhosa",
"yi":"Yiddish",
"yo":"Yoruba",
"za":"Zhuang",
"zh":"Chinese",
"zu":"Zulu",

}

export const franc_languages = {
    "cmn": "Mandarin Chinese",
    "spa": "Spanish",
    "eng": "English",
    "rus": "Russian",
    "arb": "Standard Arabic",
    "ben": "Bengali",
    "hin": "Hindi",
    "por": "Portuguese",
    "ind": "Indonesian",
    "jpn": "Japanese",
    "fra": "French",
    "deu": "German",
    "jav": "Javanese",
    "kor": "Korean",
    "tel": "Telugu",
    "vie": "Vietnamese",
    "mar": "Marathi",
    "ita": "Italian",
    "tam": "Tamil",
    "tur": "Turkish",
    "urd": "Urdu",
    "guj": "Gujarati",
    "pol": "Polish",
    "ukr": "Ukrainian",
    "kan": "Kannada",
    "mai": "Maithili",
    "mal": "Malayalam",
    "pes": "Iranian Persian",
    "mya": "Burmese",
    "swh": "Swahili",
    "sun": "Sundanese",
    "ron": "Romanian",
    "pan": "Panjabi",
    "bho": "Bhojpuri",
    "amh": "Amharic",
    "hau": "Hausa",
    "fuv": "Nigerian Fulfulde",
    "bos": "Bosnian",
    "hrv": "Croatian",
    "nld": "Dutch",
    "srp": "Serbian",
    "tha": "Thai",
    "ckb": "Central Kurdish",
    "yor": "Yoruba",
    "uzn": "Northern Uzbek",
    "zlm": "Malay",
    "ibo": "Igbo",
    "npi": "Nepali",
    "ceb": "Cebuano",
    "skr": "Saraiki",
    "tgl": "Tagalog",
    "hun": "Hungarian",
    "azj": "North Azerbaijani",
    "sin": "Sinhala",
    "koi": "Komi-Permyak",
    "ell": "Modern Greek",
    "ces": "Czech",
    "mag": "Magahi",
    "run": "Rundi",
    "bel": "Belarusian",
    "plt": "Plateau Malagasy",
    "qug": "Chimborazo Highland Quichua",
    "mad": "Madurese",
    "nya": "Nyanja",
    "zyb": "Yongbei Zhuang",
    "pbu": "Northern Pashto",
    "kin": "Kinyarwanda",
    "zul": "Zulu",
    "bul": "Bulgarian",
    "swe": "Swedish",
    "lin": "Lingala",
    "som": "Somali",
    "hms": "Southern Qiandong Miao",
    "hnj": "Hmong Njua",
    "ilo": "Iloko",
    "kaz": "Kazakh",
    "uig": "Uighur",
    "hat": "Haitian",
    "khm": "Khmer",
    "prs": "Dari",
    "hil": "Hiligaynon",
    "sna": "Shona",
    "tat": "Tatar",
    "xho": "Xhosa",
    "hye": "Armenian",
    "min": "Minangkabau",
    "afr": "Afrikaans",
    "lua": "Luba-Lulua",
    "sat": "Santali",
    "bod": "Tibetan",
    "tir": "Tigrinya",
    "fin": "Finnish",
    "slk": "Slovak",
    "tuk": "Turkmen",
    "dan": "Danish",
    "nob": "Norwegian Bokmål",
    "suk": "Sukuma",
    "als": "Tosk Albanian",
    "sag": "Sango",
    "nno": "Norwegian Nynorsk",
    "heb": "Hebrew",
    "mos": "Mossi",
    "tgk": "Tajik",
    "cat": "Catalan",
    "sot": "Southern Sotho",
    "kat": "Georgian",
    "bcl": "Central Bikol",
    "glg": "Galician",
    "lao": "Lao",
    "lit": "Lithuanian",
    "umb": "Umbundu",
    "tsn": "Tswana",
    "vec": "Venetian",
    "nso": "Pedi",
    "ban": "Balinese",
    "bug": "Buginese",
    "knc": "Central Kanuri",
    "kng": "Koongo",
    "ibb": "Ibibio",
    "lug": "Ganda",
    "ace": "Achinese",
    "bam": "Bambara",
    "tzm": "Central Atlas Tamazight",
    "ydd": "Eastern Yiddish",
    "kmb": "Kimbundu",
    "lun": "Lunda",
    "shn": "Shan",
    "war": "Waray",
    "dyu": "Dyula",
    "wol": "Wolof",
    "kir": "Kirghiz",
    "nds": "Low German",
    "fuf": "Pular",
    "mkd": "Macedonian",
    "vmw": "Makhuwa",
    "zgh": "Standard Moroccan Tamazight",
    "ewe": "Ewe",
    "khk": "Halh Mongolian",
    "slv": "Slovenian",
    "ayr": "Central Aymara",
    "bem": "Bemba",
    "emk": "Eastern Maninkakan",
    "bci": "Baoulé",
    "bum": "Bulu",
    "epo": "Esperanto",
    "pam": "Pampanga",
    "tiv": "Tiv",
    "tpi": "Tok Pisin",
    "ven": "Venda",
    "ssw": "Swati",
    "nyn": "Nyankole",
    "kbd": "Kabardian",
    "iii": "Sichuan Yi",
    "yao": "Yao",
    "lvs": "Standard Latvian",
    "quz": "Cusco Quechua",
    "src": "Logudorese Sardinian",
    "rup": "Macedo-Romanian",
    "sco": "Scots",
    "tso": "Tsonga",
    "men": "Mende",
    "fon": "Fon",
    "nhn": "Central Nahuatl",
    "dip": "Northeastern Dinka",
    "kde": "Makonde",
    "kbp": "Kabiyè",
    "tem": "Timne",
    "toi": "Tonga",
    "ekk": "Standard Estonian",
    "snk": "Soninke",
    "cjk": "Chokwe",
    "ada": "Adangme",
    "aii": "Assyrian Neo-Aramaic",
    "quy": "Ayacucho Quechua",
    "rmn": "Balkan Romani",
    "bin": "Bini",
    "gaa": "Ga",
    "ndo": "Ndonga",
}